### ISSUE TITLE
does not support use_frameworks! on ios

### ISSUE THREAD

**Issue by ayushin** [Eddayy/flutter_star_prnt#1]
```Include of non-modular header inside framework module 'flutter_star_prnt.FlutterStarPrntPlugin': '/Users/alexis/Work/aahi/aahi_sell/ios/Pods/StarIO/StarIO.framework/Headers/SMPortSwift.h'```

**Comment by ayushin** [comment]
One should refer to the official Star SDK for proper integration - it solved my problem.

**Comment by Eddayy** [comment]
Hi may I know how you managed to solve the problem?

**Comment by ayushin** [comment]
You'll think I am crazy but I no longer remember! I think for once I was no longer using !use_frameworks, but i am not sure, i am sorry, crazy busy these days
