### ISSUE TITLE
Printing Image from Url not working

### ISSUE THREAD

**Issue by Eldhose-Islet** [Eddayy/flutter_star_prnt#10]
in android  code in `FlutterStarPrntPlugin.kt` is  
 `val imageUri: Uri = Uri.parse(it.containsKey("appendBitmap").toString())`
which should be
 `val imageUri: Uri = Uri.parse(it.get("appendBitmap").toString())`

And in iOS I guess it is not implemented.
```
} else if (command["appendBitmap"] != nil) {

} else if (command["appendBitmapText"] != nil) {
```

**Comment by Eddayy** [comment]
thx for noticing, the typo is fixed and appendBitmap in implemented for IOS in 1.0.6
