### ISSUE TITLE
Port discovery on emulator

### ISSUE THREAD

**Issue by viktordineout** [Eddayy/flutter_star_prnt#14]
Hi there. Thanks for a great contribution.

I'm trying to discover a mC-Print3 printer. It's connected directly to a router with a ethernet cable.
However portDiscovery returns a empty list when using Android Emulator. My Mac is connected through wi-fi on the same router.

I'm calling the function as such:
`StarPrnt.portDiscovery(StarPortType.All).then(...)`

Are there any restrictions regarding the emulator I should know about? Is this not perhaps possible at all?

Thanks!

**Comment by Eldhose-Islet** [comment]
I think a real printer doesn't work with the android emulator. But it works with an iOS simulator. This is because android emulator has no direct access to the real network. Internet is shared using a different mechanism. You should use try in real device for printing.

**Comment by viktordineout** [comment]
Thank you @Eldhose-Islet for a quick reply.
I think so too. It works on a real device.
