### ISSUE TITLE
Doesn't print bold text & Doesn't center the text [enableEmphsis, appendEmphasis]

### ISSUE THREAD

**Issue by utkarsh-UK** [Eddayy/flutter_star_prnt#2]
I'm having problems with printing bold text. It simply doesn't print the text if I make it bold.

`// commands.push(rasterMap);
        // commands.push({'enableEmphasis': true});
        // commands.push({'appendAlignment': 'Center'});
        commands
            .push({'appendEmphasis': '            ${takeaway.orderType}\n'});
        // commands.push({'appendAlignment': 'Left'});
        commands.push({'appendEmphasis': 'Customer Details:\n'});
        // commands.push({'enableEmphasis': false});
        commands.push({
          'appendBitmapText': '${takeaway.customerName}\n'
              '${takeaway.customerContact}\n'
              '${takeaway.address}\n'
        });
        // commands.push({'enableEmphasis': true});
        commands.push({'appendEmphasis': 'Order Details:\n'});
        // commands.push({'enableEmphasis': false});
        commands.push({
          'appendBitmapText': 'Date & Time: $timestamp\n'
              'Order ID: ${takeaway.id}\n'
        });
        commands.push({'appendBitmapText': 'Payment Status: '});
        // commands.push({'enableEmphasis': true});
        commands.push({'appendEmphasis': '${takeaway.paymentStatus}\n'});
        // commands.push({'enableEmphasis': false});
        commands.push({'appendBitmapText': 'Payment Mode: '});
        // commands.push({'enableEmphasis': true});
        commands.push({'appendEmphasis': '${takeaway.paymentMode}\n'});
        // commands.push({'enableEmphasis': false});
        commands.push({
          'appendBitmapText': '--------------------------------------\n'
              'ITEM                       QTY   TOTAL\n'
              '$itemsString'
              '--------------------------------------\n'
        });
        // commands.push({'enableEmphasis': true});
        commands.push({
          'appendEmphasis': '$discountString'
              'Total                            $totalPrice\n'
        });
        // commands.push({'enableEmphasis': false});
        commands.push({
          'appendBitmapText': '--------------------------------------\n'
              '${takeaway.restaurantName}\n'
              '${restaurant.firstLineAddress}, ${restaurant.street},\n'
              '${restaurant.town}, ${restaurant.state},\n'
              '${restaurant.postCode},\n'
              '\n'
              'VAT No: ${restaurant.vatRegistration}\n'
        });
        // commands.push({'appendAlignment': 'Center'});
        commands.push({
          'appendBitmapText': '            THANK YOU          \n'
              '            $receiptTime          \n'
        });

        commands.push({'appendCutPaper': "FullCutWithFeed"});`

As you can see, I've tried using enableEphasis and appendEmphasis. Please help me here if I'm doing something wrong. I'm attaching the print image (Yellow highlights are the areas I want to print bold text
![InkedIMG-20200907-WA0016_LI](https://user-images.githubusercontent.com/42633223/92464924-7faeeb80-f1eb-11ea-9871-531f585bfbc0.jpg)
). The text I want to bold just simply doesn't print.

**Comment by Eddayy** [comment]
Hi utkarsh-UK, sorry but this is a limitation on the appendBitmapText function, internally it just renders text into a bitmap. I am planning to support for richtext in the future. Do note emphassis is only supported for printers with starprnt emulation. You can read more here: https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/api_starioext_i_command_builder.html

**Comment by Eddayy** [comment]
Recommend you switch to appendbitmapwidget or appendbitmapbyte in version 2.2.0 for better formatting

**Comment by brijeshbodariya** [comment]
> switch to appendbitmapwidget or appendbitmapbyte in version 2.2.0 fo

but @Eddayy i am not able to print this appendbitmapwidget.
