### ISSUE TITLE
WHY I got : W/BluetoothAdapter(31774): getBluetoothService() called with no BluetoothManagerCallback on my FLUTTER APP

### ISSUE THREAD

**Issue by sirinebhsn** [Eddayy/flutter_star_prnt#31]
HEllo I'm trying to connect devices with bluetooth. it's done for scanning and displaying devices But When I choose one of these devices an exception telling that getBluetoothService() called with no BluetoothManagerCallback was displayed in my terminal.
I would be very thankful if you give me some suggestions to resolve this isuue

**Comment by DuQuanzhong** [comment]
hello！How Fix  this bug?  3Q
