### ISSUE TITLE
ANALYSIS ISSUE Flutter 3.10

### ISSUE THREAD

**Issue by sumonwd** [Eddayy/flutter_star_prnt#36]
Please be compatible with Flutter 3.10
![Screenshot at May 21 10-36-22](https://github.com/Eddayy/flutter_star_prnt/assets/31125805/dafbff48-96d0-466f-9ac2-12a6fdec4c0e)

**Comment by sumonwd** [comment]
@Eddayy Please

**Comment by kennetgo** [comment]
Please

**Comment by Eddayy** [comment]
i hear you, give me a day to set up flutter, it's been a while

**Comment by sumonwd** [comment]
Sure, thank you very much

**Comment by Eddayy** [comment]
@sumonwd @kennetgo updated
