### ISSUE TITLE
IOS Compile Error: Include of non-modular header inside framework module 'flutter_star_prnt.FlutterStarPrntPlugin'

### ISSUE THREAD

**Issue by sinan-can** [Eddayy/flutter_star_prnt#5]
Hello,

after I installed the plugin as it's suggested in the documentation, I got the following compile error on IOS. I tried many things that I found on google but unfortunately nothing did help.

Do you have any Idea, how I can solve this problem?

Thanks in adavce!

![image](https://user-images.githubusercontent.com/38725079/99088919-f346ed80-25cc-11eb-8991-42fcb12cc4d8.png)

**Comment by ankraj077** [comment]
Same here. Stuck for 2 days now.

**Comment by Eddayy** [comment]
Hi there, try updating to version 1.0.5 and remember read the readme. I've change dependencies, so it can be used use_framework! in the podfile
