### ISSUE TITLE
Command CompileSwift failed with a nonzero exit code

### ISSUE THREAD

**Issue by pradeep1806** [Eddayy/flutter_star_prnt#8]
Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_star_prnt-umbrella.h"
            ^
    /Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/Target Support Files/flutter_star_prnt/flutter_star_prnt-umbrella.h:13:9: note: in file included from /Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/Target Support Files/flutter_star_prnt/flutter_star_prnt-umbrella.h:13:
    #import "FlutterStarPrntPlugin.h"
            ^
    /Users/pradeep/Me/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_star_prnt-1.0.4/ios/Classes/FlutterStarPrntPlugin.h:2:9: error: include of non-modular header inside framework module 'flutter_star_prnt.FlutterStarPrntPlugin': '/Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/StarIO/StarIO.framework/Headers/SMPortSwift.h'
    #import <StarIO/SMPortSwift.h>
            ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_star_prnt-umbrella.h"
            ^
    /Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/Target Support Files/flutter_star_prnt/flutter_star_prnt-umbrella.h:13:9: note: in file included from /Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/Target Support Files/flutter_star_prnt/flutter_star_prnt-umbrella.h:13:
    #import "FlutterStarPrntPlugin.h"
            ^
    /Users/pradeep/Me/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_star_prnt-1.0.4/ios/Classes/FlutterStarPrntPlugin.h:3:9: error: include of non-modular header inside framework module 'flutter_star_prnt.FlutterStarPrntPlugin': '/Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/StarIO_Extension/StarIO_Extension.framework/Headers/StarIoExt.h'
    #import <StarIO_Extension/StarIoExt.h>
            ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_star_prnt-umbrella.h"
            ^
    /Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/Target Support Files/flutter_star_prnt/flutter_star_prnt-umbrella.h:13:9: note: in file included from /Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/Target Support Files/flutter_star_prnt/flutter_star_prnt-umbrella.h:13:
    #import "FlutterStarPrntPlugin.h"
            ^
    /Users/pradeep/Me/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_star_prnt-1.0.4/ios/Classes/FlutterStarPrntPlugin.h:4:9: error: include of non-modular header inside framework module 'flutter_star_prnt.FlutterStarPrntPlugin': '/Users/pradeep/Me/freelance_project/posable/posable-retail-pos/posable_retail_pos/ios/Pods/StarIO_Extension/StarIO_Extension.framework/Headers/StarIoExtManager.h'
    #import <StarIO_Extension/StarIoExtManager.h>
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_star_prnt'
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPad (7th generation).

**Comment by take-in** [comment]
Same
I am unable to run this in iOS 

```
⋊> ~/t/1/b/f/example on master ⨯ flutter doctor -v                                                                                              09:53:31
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/reza/development/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/reza/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone Reza (mobile) • d81429f0469936d3ba37d0788ced05e6d5924288 • ios • iOS 14.3

```

**Comment by Eddayy** [comment]
Hi there, the issue is mainly because the library from cocoapods is non-modular and when using use_framework! in podfile the build fails, I've updated to code to get the files locally and the config to be a proper swift framework . Try updating to version 1.0.5 and remember read the readme.

**Comment by pradeep1806** [comment]
Thanks Eddayy. It works fine now.
